-- Migration V31: Add correlation_id to clientes for idempotent offline sync
-- Safe rollout: Nullable column, partial unique index

-- 1. Add column (nullable)
ALTER TABLE clientes ADD COLUMN correlation_id VARCHAR(36);

-- 2. Add Unique Index (Partial)
-- Only enforces uniqueness for non-null values.
-- This allows existing rows (null) and new simple rows (null) to coexist without conflict,
-- while enforcing idempotency for offline-synced rows that provide it.
CREATE UNIQUE INDEX idx_clientes_correlation_id ON clientes(correlation_id) WHERE correlation_id IS NOT NULL;

-- 3. (Optional) Comment
COMMENT ON COLUMN clientes.correlation_id IS 'UUID generated by mobile app for idempotent creation/sync';
